version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blacklist_service_app
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/blacklist
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: blacklist_service_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blacklist
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
